openapi: 3.0.0
info:
  description: This lists the details for WidgetConfiguration-Service
  version: 0.1.2
  title: WidgetConfiguration Service API
  termsOfService: 'http://alight.com/terms'
  contact:
    name: Alight API Team
    email: api@alight.com
    url: 'https://alight.com/apis'
  license:
    name: Proprietary License
servers:
  - url: 'https://api-dv.alight.com/api'
    description: Development environment
  - url: 'https://api-qa.alight.com/api'
    description: Quality Assurance environment
  - url: 'https://api-ste.alight.com/api'
    description: Stress Test environment
  - url: 'https://api-qc.alight.com/api'
    description: Quality Control environment
  - url: 'https://api.alight.com/api'
    description: Production environment
  - url: 'http://localhost/api'
    description: Local Development environment
paths:
  '/channel/widgetconfigurations/channel/widgetConfigurations/{widget}':
    get:
      tags:
        - Get Widget Configurations
      summary: >-
        Returns list of configurations required for requested widget for e.g.
        header,footer,tiles,upc,etc. Ideally each widget defines it's ConfigSet
        which represents all configurations(text, expression, assets,
        params,etc) required for any particular widget.
      operationId: getWidgetConfiguration
      description: >
        By passing in the appropriate widget name, API will return the list of
        widget configurations for the corresponding ConfigSet of the widget.
      parameters:
        - name:   alightPersonSessionToken
          in: header
          description: Session token generated by startSessionForPerson call
          schema:
            type: string
          required: true
          example:
            $ref: '#/components/examples/authorization-header'
        - name: alightRequestHeader
          in: header
          description: >-
            Request header which contains 'locale','roleId' and
            'consumerReferenceId'
          schema:
            type: string
          required: true
          example:
            $ref: '#/components/examples/request-header'
        - name: UseSecondaryDataCache
          in: header
          description: >-
            If the value of this request header is true, then the configurations
            will be resolved from configured secondary redis instance.
          schema:
            type: boolean
          required: false
        - name: SecondaryRedisAlias
          in: header
          description: >-
            This is the name of secondary redis alias from where we want to
            fetch the configuration if the secondary redis is enabled. If
            UseSecondaryDataCache is true, then by default SecondaryRedisAlias's
            value will be passed as "default", if not passed explicitly.
          schema:
            type: string
          required: false
        - name: widget
          in: path
          description: Name of the widget to be returned
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >-
            API returns configurations (Links, Text, Expression, Asset etc.) of
            the requested widget(e.g.:-tile, header,footer,upc) in json form.
            The response modelis described below under the schema
            section(defined as $ref) and the sample output is described under
            the example section.
          content:
            application/json:
              schema:
                type: array
                items: null
                $ref: '#/components/schemas/widgetResponse'
                example:
                  $ref: '#/components/examples/WidgetResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/channel/widgetconfigurations/channel/widgetConfigurations/{widget}/public':
    get:
      tags:
        - Get Configurations from requested config set for Pre Auth Users
      summary: >-
        Returns list of configurations required based on requested configSet
        which represents all configurations(text, expression, assets, etc). In
        case config set contains any configuration which is dependent on AHUser,
        then that particular configuration will return error in response.
      operationId: getPreAuthWidgetConfiguration
      description: >
        By passing in the appropriate config set name, API will return the list
        of configurations for the corresponding ConfigSet of the widget.
      parameters:
        - name: alightRequestHeader
          in: header
          description: >-
            Request header which contains 'locale','clientId' and
            'consumerReferenceId'
          schema:
            type: string
          required: true
          example:
            $ref: '#/components/examples/request-header'
        - name: UseSecondaryDataCache
          in: header
          description: >-
            If the value of this request header is true, then the configurations
            will be resolved from configured secondary redis instance.
          schema:
            type: boolean
          required: false
        - name: SecondaryRedisAlias
          in: header
          description: >-
            This is the name of secondary redis alias from where we want to
            fetch the configuration if the secondary redis is enabled. If
            UseSecondaryDataCache is true, then by default SecondaryRedisAlias's
            value will be passed as "default", if not passed explicitly.
          schema:
            type: string
          required: false
      responses:
        '200':
          description: >-
            API returns configurations (Links, Text, Expression, Asset etc.) of
            the requested config set.The response modelis described below under
            the schema section(defined as $ref) and the sample output is
            described under the example section.
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/APIResponse'
                example:
                  $ref: '#/components/examples/APIResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/channel/widgetConfigurations/validateblackout/public':
    get:
      tags:
        - Get blackout status for given clientId and brokerUserId. 
      summary: >-
        Returns "BLACKOUT" if blackout is active for given clientId and brokerUserId otherwise returns "ALLOW"
        
      operationId: validateblackout
      description: >
        By passing in the appropriate clientId and brokerUserId API will return blackout status(BLACKOUT/ALLOW).
      parameters:
        - name: alightRequestHeader
          in: header
          description: >-
            Request header which contains 'locale','clientId' and
            'consumerReferenceId'
          schema:
            type: string
          required: true
          example:
            $ref: '#/components/examples/request-header'

        - name: brokerUserId
          in: query
          description: >-
            This is used to pass brokerUserId.(for example Portal)
          schema:
            type: string
          required: true
      responses:
        '200':
          description: >-
            API returns blackout status of given clientId and brokerUserId.
            the schema section(defined as $ref) and the sample output is
            described under the example section.
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/validateblackoutAPIResponse'
                example:
                  $ref: '#/components/examples/validateblackoutAPIResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                
  /channel/widgetconfigurations/channel/configurationList/get:
    post:
      tags:
        - >-
          Fetch Configurations List e.g. Link, Text, Parameter, Expression or
          UPC configurations based on the operation
      summary: >-
        Fetches configurations based on the config key set passed under body
        when operation is "configSet" or fetches UPC configurations when
        operation is "upc".
      operationId: getConfigurationList
      description: 'Returns configurations List text, link, parameter etc.'
      parameters:
        - name: alightSecureSessionToken or alightPersonSessionToken
          in: header
          description: Access token returned from /zuul-service/ /startSessionForPerson
          schema:
            type: string
          required: true
          example:
            $ref: '#/components/examples/authorization-header'
        - name: ASG-SessionToken
          in: header
          description: Optional parameter - can be used to override the participant details
          required: false
          schema:
            type: string
        - name: alightRequestHeader
          in: header
          description: >-
            Request header which contains 'locale','roleId' and
            'consumerReferenceId'
          schema:
            type: string
          required: true
          example:
            $ref: '#/components/examples/request-header'
        - name: UseSecondaryDataCache
          in: header
          description: >-
            If the value of this request header is true, then the configurations
            will be resolved from configured secondary redis instance.
          schema:
            type: boolean
          required: false
        - name: SecondaryRedisAlias
          in: header
          description: >-
            This is the name of secondary redis alias from where we want to
            fetch the configuration if the secondary redis is enabled. If
            UseSecondaryDataCache is true, then by default SecondaryRedisAlias's
            value will be passed as "default", if not passed explicitly.
          schema:
            type: string
          required: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigSet'
      responses:
        '200':
          description: configuration details
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/APIResponse'
                example:
                  - $ref: '#/components/examples/APIResponse'
                  - $ref: '#/components/examples/WidgetResponseUPC'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /channel/widgetconfigurations/channel/configurationList/get/public:
    post:
      tags:
        - >-
          Fetch Pre Auth Configurations List e.g. Link, Text, Parameter,
          Expression
      summary: >-
        Fetches configurations valid for pre Auth Usersbased on the config key
        set passed under body.
      operationId: getPreAuthWidgetConfigurationList
      description: 'Returns configurations List text, link, parameter etc.'
      parameters:
        - name: alightRequestHeader
          in: header
          description: >-
            Request header which contains 'locale','roleId' and
            'consumerReferenceId'
          schema:
            type: string
          required: true
          example:
            $ref: '#/components/examples/request-header'
        - name: UseSecondaryDataCache
          in: header
          description: >-
            If the value of this request header is true, then the configurations
            will be resolved from configured secondary redis instance.
          schema:
            type: boolean
          required: false
        - name: SecondaryRedisAlias
          in: header
          description: >-
            This is the name of secondary redis alias from where we want to
            fetch the configuration if the secondary redis is enabled. If
            UseSecondaryDataCache is true, then by default SecondaryRedisAlias's
            value will be passed as "default", if not passed explicitly.
          schema:
            type: string
          required: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigSet'
      responses:
        '200':
          description: configuration details
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/APIResponse'
                example:
                  $ref: '#/components/examples/APIResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  examples:
    authorization-header:
      summary: Example of authorization-header parameter
      value: Bearer <access_token>
    request-header:
      summary: Example of alight-request-header parameter
      value:
        locale: en_US
        roleId: '19920_1.0-E:@PPT@'
    WidgetResponse:
      value:
        - $ref: '#/components/examples/WidgetResponseHeader'
        - $ref: '#/components/examples/WidgetResponseFooter'
        - $ref: '#/components/examples/WidgetResponseTiles'
        - $ref: '#/components/examples/WidgetResponseUPC'
    WidgetResponseHeader:
      summary: Example of WidgetResponse-Header
      value:
        - HEADER_FOOTER_VERSION:
            type: parameter
            value: '1'
          IS_HEADER_FOOTER_V2:
            type: expression
            value: true
    WidgetResponseFooter:
      summary: Example of WidgetResponse-Footer
      value:
        - FOOTER_COOKIE_NOTICE_FINDOUT_MORE_BTN:
            id: FOOTER_COOKIE_NOTICE_FINDOUT_MORE_BTN
            type: TEXT
            value: Find Out More
          isShowDebug:
            id: isShowDebug
            type: EXPR
            value: true
    WidgetResponseTiles:
      summary: Example of WidgetResponse-Tiles
      value:
        - tileResponse:
            cellCSS: al-gutter-col al-w25 al-720-w50 al-480-w50 al-320-w100
            dataTile: false
            portletTitle: Highlights for You
            columns: 4
            rows: 1
            namespace: >-
              Tile_WAR_ahtilesportlet_INSTANCE_8949a14a-3eff-434c-ae32-159aaefba503
    WidgetResponseUPC:
      summary: Example of WidgetResponse-UPC
      value:
        - asset:
            Dashboard:
              OpsNoEditsDefects:
                assetType: assetgroup
                assetValue:
                  DashboardName:
                    assetType: text
                    assetValue: operations
                    assetKey: oper_txt_key
                assetKey: OpsNoEditsDefects
    APIResponse:
      summary: Example of Debug API response
      value:
        - text:
            AA: Army - Americas
          expr:
            ALWAYS_PASS: true
            Jcalc_Base_Boolean:
              C: true
          param:
            Portal_Pams_404K: 404
          hro:
            IS_UDP_ENABLED: true
          edit:
            '91531001':
              classification: FIELD
              msg: >-
                TestCfg field is blank. Enter information before continuing.
                (Message Number&#58; 91531001)
              severity: ERROR
              fieldName: null
    validateblackoutAPIResponse:
      summary: Example of validateblackout API response
      value:
        - status: "BLACKOUT/ALLOW"     
        
            
  schemas:
    widgetResponse:
      type: object
      properties:
        expression:
          type: string
        parameter:
          type: string
        link:
          type: string
        asset:
          type: string
        text:
          type: string
        validvalues:
          type: string
    APIResponse:
      type: object
      properties:
        expression:
          type: string
        parameter:
          type: string
        link:
          type: string
        asset:
          type: string
        text:
          type: string
        validvalues:
          type: string
    validateblackoutAPIResponse:
      type: object
      properties:
        status:
          type: string

    ConfigSet:
      type: object
      properties:
        lineage:
          type: string
        locale:
          type: string
        operation:
          type: string
        targetDate:
          type: string
        textKeys:
          type: Object
          $ref: '#/components/schemas/keys'
        exprKeys:
          type: Object
          $ref: '#/components/schemas/keys'
        paramKeys:
          type: Object
          $ref: '#/components/schemas/keys'
        linkKeys:
          type: Object
          $ref: '#/components/schemas/keys'
        assetKeys:
          type: Object
          $ref: '#/components/schemas/keys'
        validvalueKeys:
          type: Object
          $ref: '#/components/schemas/keys'
        upcKey:
          type: Object
          $ref: '#/components/schemas/UPCkey'
    keys:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
    UPCkey:
      type: array
      items:
        type: object
        properties:
          widgetName:
            type: string
          widgetInstanceId:
            type: string
          requestParam:
            type: object
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
